### ISSUE TITLE
[BUG] bukkitId not recongnized option in most recent release

### ISSUE THREAD

**Issue by jippi** [Silthus/plugin-downloader#63]
**Describe the bug**
Need more recent release/tag 

**To Reproduce**

This config file and run the program

```
curseApiKey: xxxxx
plugins:
  worldedit:
    file: WorldEdit.jar
    bukkitId: 31043
```

**Expected behavior**
It would work
